TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Sitegeist.CriticalMass': TRUE
    userInterface:
      navigateComponent:
        nodeTree:
          presets:
            default:
              baseNodeType: 'Sitegeist.CriticalMass:PageTreeMixin'

Sitegeist:

  CriticalMass:

    automaticNodeHirarchy:

#      'Sitegeist.CriticalMass:ExampleNode':
#        root: "${q(node).parents().filter('[instanceof Sitegeist.CriticalMass:ExampleCollection]').slice(-1, 1).get(0)}"
#        path:
#          -
#            type: "Sitegeist.CriticalMass:ExampleCollection"
#            properties:
#              title: "${Date.year(q(node).property('date'))}"
#              uriPathSegment: "${Date.year(q(node).property('date'))}"
#          -
#            type: "Sitegeist.CriticalMass:ExampleCollection"
#            properties:
#              title: "${Date.year(q(node).property('date'))}"
#              uriPathSegment: "${Date.month(q(node).property('date'))}"
