TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Sitegeist.CriticalMass': TRUE
    userInterface:
      navigateComponent:
        nodeTree:
          presets:
            default:
              baseNodeType: 'Sitegeist.CriticalMass:PageTreeMixin'
