TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Sitegeist.CriticalMass': TRUE
    userInterface:
      navigateComponent:
        nodeTree:
          presets:
            default:
              baseNodeType: 'Sitegeist.CriticalMass:PageTreeMixin'

Sitegeist:
  CriticalMass:

    eelContext:
      String: 'TYPO3\Eel\Helper\StringHelper'
      Array: 'TYPO3\Eel\Helper\ArrayHelper'
      Date: 'TYPO3\Eel\Helper\DateHelper'
      Configuration: 'TYPO3\Eel\Helper\ConfigurationHelper'
      Math: 'TYPO3\Eel\Helper\MathHelper'
      Json: 'TYPO3\Eel\Helper\JsonHelper'
      Security: 'TYPO3\Eel\Helper\SecurityHelper'
      Translation: 'TYPO3\Flow\I18n\EelHelper\TranslationHelper'
      Type: 'TYPO3\Eel\Helper\TypeHelper'
      I18n: 'TYPO3\Flow\I18n\EelHelper\TranslationHelper'

    automaticNodeHirarchy:
#      'Sitegeist.CriticalMass:ExampleNode':
#        root: "${q(node).parents().filter('[instanceof Sitegeist.CriticalMass:ExampleCollection]').slice(-1, 1).get(0)}"
#        path:
#          -
#            type: "Sitegeist.CriticalMass:ExampleCollection"
#            properties:
#              title: "${Date.year(q(node).property('date'))}"
#              uriPathSegment: "${Date.year(q(node).property('date'))}"
#          -
#            type: "Sitegeist.CriticalMass:ExampleCollection"
#            properties:
#              title: "${Date.year(q(node).property('date'))}"
#              uriPathSegment: "${Date.month(q(node).property('date'))}"
