Sitegeist:
  CriticalMass:
    automaticNodeHierarchy:
#      'Sitegeist.CriticalMass:ExampleNode':
#        root: "${q(node).parents().filter('[instanceof Sitegeist.CriticalMass:ExampleNodeCollection]').slice(-1, 1).get(0)}"
#        path:
#          -
#            name: "${'node-event-year-' + (q(node).property('startDate') ? Date.year(q(node).property('startDate')) : 'no-year')}"
#            type: "${'Sitegeist.CriticalMass:ExampleNodeCollection'}"
#            properties:
#              title: "${q(node).property('startDate') ? Date.year(q(node).property('startDate')) : 'no-year'}"
#              uriPathSegment: "${q(node).property('startDate') ? Date.year(q(node).property('startDate')) : 'no-year'}"
#          -
#            name: "${'node-event-month-' + (q(node).property('startDate') ? Date.month(q(node).property('startDate')) : 'no-month')}"
#            type: "${'Sitegeist.CriticalMass:ExampleNodeCollection'}"
#            properties:
#              title: "${q(node).property('startDate') ? Date.month(q(node).property('startDate')) : 'no-month'}"
#              uriPathSegment: "${q(node).property('startDate') ? Date.month(q(node).property('startDate')) : 'no-month'}"
