Sitegeist:
  CriticalMass:
    #
    # See README.md for the configuration options
    #

    # automatically create hierarchies for specific nodeTypes
    automaticNodeHierarchy: {}

    # import presets
    import: {}

    # export presets
    export: {}

Neos:
  Neos:
    fusion:
      autoInclude:
        'Sitegeist.CriticalMass': true
  Fusion:
    defaultContext:
      'CriticalMass.Node': 'Sitegeist\CriticalMass\Eel\Helper\NodeHelper'
