Sitegeist:
  CriticalMass:
    automaticNodeHierarchy: []

#      # the configuration for the nodeType Sitegeist.CriticalMass:ExampleNode
#      'Sitegeist.CriticalMass:ExampleNode':
#
#        # detect the root-collection node that will contain the automatic created node hierarchie
#        root: "${q(node).parents().filter('[instanceof Sitegeist.CriticalMass:ExampleNodeCollection]').slice(-1, 1).get(0)}"
#
#        # define the levels of the node hierarchie that is created inside the root node
#        path:
#
#          # level 1 year
#          -
#            # the type and nodename of the hierarchy-node
#            type: 'Sitegeist.CriticalMass:ExampleNodeCollection'
#            name: "${'node-event-year-' + (q(node).property('startDate') ? Date.year(q(node).property('startDate')) : 'no-year')}"
#
#            # properties that are applied only on node creation and can be edited afterwards
#            properties:
#              title: "${q(node).property('startDate') ? Date.year(q(node).property('startDate')) : 'no-year'}"
#              uriPathSegment: "${q(node).property('startDate') ? Date.year(q(node).property('startDate')) : 'no-year'}"
#
#          # level 2 month
#          -
#            # the type and nodename of the hierarchy-node
#            type: 'Sitegeist.CriticalMass:ExampleNodeCollection'
#            name: "${'node-event-month-' + (q(node).property('startDate') ? Date.month(q(node).property('startDate')) : 'no-month')}"
#
#            # properties that are applied only on node creation and can be edited afterwards
#            properties:
#              title: "${q(node).property('startDate') ? Date.month(q(node).property('startDate')) : 'no-month'}"
#              uriPathSegment: "${q(node).property('startDate') ? Date.month(q(node).property('startDate')) : 'no-month'}"


Neos:
  Neos:
    fusion:
      autoInclude:
        'Sitegeist.CriticalMass': true
  Fusion:
    defaultContext:
      'CriticalMass.Node': 'Sitegeist\CriticalMass\Eel\Helper\NodeHelper'
